delete from user_visa;
delete from visa;
delete from visa_category;

INSERT INTO visa_category (category, english_name, korean_name) VALUES
("A-1", "Diplomat", "외교"),
("A-2", "Government official", "공무"),
("A-3", "Agreement", "협정"),
("B-1", "Visa exemption", "사증면제"),
("B-2", "Tourist/transit", "관광통과"),
("C-1", "Temporary news coverage", "일시취재"),
("C-2", "Short-term business", "단기상용"),
("C-3", "Short-term visit", "단기방문"),
("C-4", "Short-term employee", "단기취업"),
("D-1", "Artist", "문화예술"),
("D-2", "Students", "유학"),
("D-3", "Industrial trainee", "산업연수"),
("D-4", "General trainee", "일반연수"),
("D-5", "Journalism", "취재"),
("D-6", "Religion", "종교"),
("D-7", "Intra-Company Transfer", "주재"),
("D-8", "Corporate investor", "기업투자"),
("D-9", "International trade", "무역경영"),
("D-10", "Job Seeking", "구직"),
("E-1", "Professor", "교수"),
("E-2", "Foreign language instructor", "회화지도"),
("E-3", "Research", "연구"),
("E-4", "Technology transfer", "기술지도"),
("E-5", "Professional employment", "전문직업"),
("E-6", "Artistic performer", "예술흥행"),
("E-7", "Designated activities", "특정활동"),
("E-8", "Training employment", "연수취업"),
("E-9", "Non-professional employment", "비전문취업"),
("E-10", "Crew employee", "선원취업"),
("F-1", "Visiting or joining family", "방문동거"),
("F-2", "Resident", "거주"),
("F-3", "Accompanying spouse / child", "동반"),
("F-4", "Overseas Korean", "재외동포"),
("F-5", "Permanent resident", "영주"),
("F-6", "Marriage to Korean Citizen", "결혼이민"),
("G-1", "Miscellaneous", "기타"),
("H-1", "Working holiday", "관광취업"),
("H-2", "Working visit", "방문취업제"),
("M-1", "Military", "군인"),
("T-1", "Tourist landing", "관광상륙")
;


INSERT INTO visa (subcategory, description, visa_category_id) VALUES
("B-2-1", "Tourist/Transit (General)", (SELECT id FROM visa_category WHERE category = "B-2")),
("B-2-2", "Tourist/Transit (Jeju)", (SELECT id FROM visa_category WHERE category = "B-2")),
("C-3-1", "Short-term General", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-2", "Group Tourist", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-3", "Medical Tourist", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-4", "Business Visitor (General)", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-5", "Business Visitor (Agreement)", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-6", "Business Visitor (Sponsored)", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-8", "Short-term Visitor for overseas Koreans", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-9", "Ordinary Tourist", (SELECT id FROM visa_category WHERE category = "C-3")),
("C-3-10", "Airside Direct Transit", (SELECT id FROM visa_category WHERE category = "C-3")),
("D-2-1", "Associate Degree", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-2-2", "Bachelor's Degree", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-2-3", "Master's Degree", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-2-4", "Doctoral Degree", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-2-5", "Research Study", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-2-6", "Exchange Student", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-2-7", "Student Invited by the Korean Government", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-2-8", "Short Term Study", (SELECT id FROM visa_category WHERE category = "D-2")),
("D-3-11", "Industrial Trainee", (SELECT id FROM visa_category WHERE category = "D-3")),
("D-3-12", "Industrial Trainee (Technology)", (SELECT id FROM visa_category WHERE category = "D-3")),
("D-3-13", "Industrial Trainee (Plant)", (SELECT id FROM visa_category WHERE category = "D-3")),
("D-3-14", "Industrial Trainee (Others)", (SELECT id FROM visa_category WHERE category = "D-3")),
("D-4-1", "Korean Language Trainee", (SELECT id FROM visa_category WHERE category = "D-4")),
("D-4-2", "General Trainee (Others)", (SELECT id FROM visa_category WHERE category = "D-4")),
("D-4-3", "Elementary/Middle/High School Student", (SELECT id FROM visa_category WHERE category = "D-4")),
("D-4-5", "Trainee Chef (Korean Cuisine)", (SELECT id FROM visa_category WHERE category = "D-4")),
("D-4-6", "General Trainee (Private Institute)", (SELECT id FROM visa_category WHERE category = "D-4")),
("D-4-7", "Foreign Language Trainee", (SELECT id FROM visa_category WHERE category = "D-4")),
("D-8-1", "Establishing a Local Business", (SELECT id FROM visa_category WHERE category = "D-8")),
("D-8-2", "Venture Capital", (SELECT id FROM visa_category WHERE category = "D-8")),
("D-8-3", "Unincorporated Enterprise", (SELECT id FROM visa_category WHERE category = "D-8")),
("D-8-4", "Technology and Business Start-up", (SELECT id FROM visa_category WHERE category = "D-8")),
("D-10-1", "Job Seeker", (SELECT id FROM visa_category WHERE category = "D-10")),
("D-10-2", "Business Startup", (SELECT id FROM visa_category WHERE category = "D-10")),
("E-2-1", "Foreign Language Instructor (General)", (SELECT id FROM visa_category WHERE category = "E-2")),
("E-2-2", "Teaching Assistant", (SELECT id FROM visa_category WHERE category = "E-2")),
("E-2-91", "Foreign Language Instructor (by FTA)", (SELECT id FROM visa_category WHERE category = "E-2")),
("E-6-1", "Artist", (SELECT id FROM visa_category WHERE category = "E-6")),
("E-6-2", "Hotel and Adult Entertainment", (SELECT id FROM visa_category WHERE category = "E-6")),
("E-6-3", "Athlete", (SELECT id FROM visa_category WHERE category = "E-6")),
("E-7-1", "Foreign National of Special Ability", (SELECT id FROM visa_category WHERE category = "E-7")),
("E-8", "Seasonal Worker", (SELECT id FROM visa_category WHERE category = "E-8")),
("E-9-1", "Manufacturing", (SELECT id FROM visa_category WHERE category = "E-9")),
("E-9-2", "Construction", (SELECT id FROM visa_category WHERE category = "E-9")),
("E-9-3", "Agriculture", (SELECT id FROM visa_category WHERE category = "E-9")),
("E-9-4", "Fishery", (SELECT id FROM visa_category WHERE category = "E-9")),
("E-9-5", "Service", (SELECT id FROM visa_category WHERE category = "E-9")),
("F-2-1", "Spouse of a Korean National", (SELECT id FROM visa_category WHERE category = "F-2")),
("F-2-2", "Single-entry visa for underage foreign child of Korean national", (SELECT id FROM visa_category WHERE category = "F-2")),
("F-2-3", "Single-entry resident visa for spouse of a resident visa holder (F-5)", (SELECT id FROM visa_category WHERE category = "F-2")),
("F-2-4", "Recognized refugee", (SELECT id FROM visa_category WHERE category = "F-2")),
("F-2-7", "Awarded on a points-based system", (SELECT id FROM visa_category WHERE category = "F-2")),
("F-2-99", "Awarded after 5 years on an E-2 visa", (SELECT id FROM visa_category WHERE category = "F-2")),
("F-4-11", "Overseas Korean", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-12", "Descendent of Overseas Korean", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-13", "Former D or E visa holder", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-14", "University Graduates", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-15", "Permanent resident of OECD country", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-16", "Corporate Executive", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-17", "Entrepreneur of $100,000", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-18", "Multinational Company", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-19", "Representative of overseas Koreans organization", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-20", "Government Employee", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-4-21", "Teacher", (SELECT id FROM visa_category WHERE category = "F-4")),
("F-5-11", "Special Talent", (SELECT id FROM visa_category WHERE category = "F-5")),
("F-6-1", "Spouse of a Korean National", (SELECT id FROM visa_category WHERE category = "F-6")),
("F-6-2", "Child Raising", (SELECT id FROM visa_category WHERE category = "F-6")),
("G-1-1", "Medical treatment due to industrial accidents and the family member", (SELECT id FROM visa_category WHERE category = "G-1")),
("G-1-2", "Undergoing medical treatments as a result of diseases or accidents", (SELECT id FROM visa_category WHERE category = "G-1")),
("G-1-3", "Involved in a lawsuit", (SELECT id FROM visa_category WHERE category = "G-1")),
("G-1-4", "Involved in a labor arbitration case", (SELECT id FROM visa_category WHERE category = "G-1")),
("G-1-5", "Refugee applicants", (SELECT id FROM visa_category WHERE category = "G-1")),
("G-1-6", "Humanitarian Status", (SELECT id FROM visa_category WHERE category = "G-1")),
("H-2-1", "Work and Visit (Family Connection)", (SELECT id FROM visa_category WHERE category = "H-2")),
("H-2-2", "Work and Visit (Parents/Spouse of D-2 Student)", (SELECT id FROM visa_category WHERE category = "H-2")),
("H-2-5", "Work and Visit (By lottery)", (SELECT id FROM visa_category WHERE category = "H-2")),
("H-2-7", "Work and Visit (Expired Visa)", (SELECT id FROM visa_category WHERE category = "H-2"))
;
